"""initial schema

Revision ID: df641a2a9783
Revises: 
Create Date: 2026-09-03 19:10:29.334434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df641a2a9783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bench_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bench_runs'))
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(), nullable=True),
    sa.Column('contact_hash', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('razorpay_customer_id', name=op.f('uq_customers_razorpay_customer_id'))
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_events'))
    )
    op.create_table('consent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('checkout','sms_stop','dashboard','dnd_sync','import')", name='ck_consent_events_source'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_consent_events_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_events'))
    )
    op.create_index('consent_lookup', 'consent_events', ['customer_id', 'channel', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('contact_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_contact_events_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_events'))
    )
    op.create_index('contact_lookup', 'contact_events', ['customer_id', 'channel', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('customer_pii',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_pii_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer_pii'))
    )
    op.create_table('mandates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('rail', sa.String(), nullable=False),
    sa.Column('max_amount_paise', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('representations_used_this_cycle', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('representation_cap', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rail IN ('upi_autopay','enach','emandate','card')", name='ck_mandates_rail'),
    sa.CheckConstraint("status IN ('pending','active','paused','revoked','expired')", name='ck_mandates_status'),
    sa.CheckConstraint('max_amount_paise > 0', name='ck_mandates_max_amount_positive'),
    sa.CheckConstraint('representations_used_this_cycle <= representation_cap', name='ck_mandates_representations_within_cap'),
    sa.CheckConstraint('representations_used_this_cycle >= 0', name='ck_mandates_representations_non_negative'),
    sa.CheckConstraint('valid_from <= valid_until', name='ck_mandates_valid_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_mandates_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandates'))
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leak_class', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('at_risk_paise', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decline_category', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("leak_class IN ('L1','L2','L3','L4','L5','L6')", name='ck_signals_leak_class'),
    sa.CheckConstraint('at_risk_paise > 0', name='ck_signals_at_risk_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_signals_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('arm', sa.String(), nullable=False),
    sa.Column('at_risk_paise', sa.Integer(), nullable=False),
    sa.Column('cost_spent_paise', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_ceiling_paise', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(), nullable=True),
    sa.Column('playbook_version', sa.Integer(), nullable=True),
    sa.Column('bench_run_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state IN ('recovered','partially_recovered','lost','expired','suppressed') AND resolved_at IS NOT NULL) OR (state NOT IN ('recovered','partially_recovered','lost','expired','suppressed') AND resolved_at IS NULL)", name='resolved_iff_terminal'),
    sa.CheckConstraint("arm IN ('control','baseline','treatment')", name='ck_cases_arm'),
    sa.CheckConstraint('at_risk_paise > 0', name='ck_cases_at_risk_positive'),
    sa.CheckConstraint('cost_ceiling_paise >= 0', name='ck_cases_cost_ceiling_non_negative'),
    sa.CheckConstraint('cost_spent_paise <= cost_ceiling_paise', name='cost_within_ceiling'),
    sa.CheckConstraint('cost_spent_paise >= 0', name='ck_cases_cost_spent_non_negative'),
    sa.ForeignKeyConstraint(['bench_run_id'], ['bench_runs.id'], name=op.f('fk_cases_bench_run_id_bench_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_cases_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_cases_signal_id_signals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index('cases_open_dedup', 'cases', ['customer_id', 'at_risk_paise'], unique=True, postgresql_where=sa.text("state NOT IN ('recovered','partially_recovered','lost','expired','suppressed')"))
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 1', name='ck_actions_attempt_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_actions_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('case_id', 'step_id', 'attempt', name='uq_actions_case_step_attempt'),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_actions_idempotency_key'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.CheckConstraint("actor_type IN ('system','user','scheduler')", name='ck_audit_events_actor_type'),
    sa.CheckConstraint('seq >= 1', name='audit_seq_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_audit_events_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('case_id', 'seq', name='audit_seq_unique')
    )
    op.create_index('audit_case_seq', 'audit_events', ['case_id', 'seq'], unique=False)
    op.create_index('audit_kind_time', 'audit_events', ['kind', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('fallback_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('statistical','llm_ranked','abstained')", name='ck_diagnoses_method'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_diagnoses_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses')),
    sa.UniqueConstraint('case_id', name=op.f('uq_diagnoses_case_id'))
    )
    op.create_table('outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('recovered_paise', sa.Integer(), nullable=False),
    sa.Column('attributed_payment_id', sa.String(), nullable=True),
    sa.Column('attributed_step_id', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('recovered','partially_recovered') OR reason_code IS NOT NULL", name='ck_outcomes_reason_code_required'),
    sa.CheckConstraint("kind IN ('recovered','partially_recovered','lost','expired','suppressed','escalated')", name='ck_outcomes_kind'),
    sa.CheckConstraint('recovered_paise >= 0', name='ck_outcomes_recovered_non_negative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_outcomes_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes')),
    sa.UniqueConstraint('case_id', name=op.f('uq_outcomes_case_id'))
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_payments_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.String(), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('total_expected_cost_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_expected_cost_paise >= 0', name='ck_plans_total_expected_cost_non_negative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_plans_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('case_id', name=op.f('uq_plans_case_id'))
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_hypotheses_confidence_range'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_hypotheses_diagnosis_id_diagnoses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses')),
    sa.UniqueConstraint('diagnosis_id', 'rank', name='uq_hypotheses_diagnosis_rank')
    )
    op.create_table('planned_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_cost_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_planned_steps_plan_id_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_steps')),
    sa.UniqueConstraint('plan_id', 'step_id', name='uq_planned_steps_plan_step')
    )
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defer_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('allow','deny','defer')", name='ck_policy_decisions_verdict'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_policy_decisions_action_id_actions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decisions')),
    sa.UniqueConstraint('action_id', 'attempt', name='uq_policy_decisions_action_attempt')
    )
    op.create_table('scheduled_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','claimed','done','failed','cancelled')", name='ck_scheduled_actions_status'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_scheduled_actions_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_scheduled_actions_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_actions'))
    )
    op.create_index('scheduled_due', 'scheduled_actions', ['due_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('scheduled_expired_claims', 'scheduled_actions', ['claim_expires_at'], unique=False, postgresql_where=sa.text("status = 'claimed'"))
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=False),
    sa.Column('slice_dimension', sa.String(), nullable=False),
    sa.Column('slice_value', sa.String(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('baseline_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('z_statistic', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_evidence_hypothesis_id_hypotheses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    # ### end Alembic commands ###

    # --- Hand-added: triggers, not something autogenerate can produce -----
    # (DATA-MODEL SS3.1, SS6). Application-level immutability is a promise
    # that survives exactly until someone writes a cleanup script; this
    # trigger is the guarantee. It makes tampering with audit_events require
    # a schema change, which is itself in version control.
    op.execute("""
        CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only (attempted %)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
    """)
    op.execute("""
        CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
    """)

    # Mutable tables' updated_at is kept current by the database, not the
    # application (DATA-MODEL SS1) -- a row touched through any path still
    # gets a correct timestamp, not just the ones application code
    # remembers to set.
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    for table in ("cases", "mandates", "bench_runs"):
        op.execute(
            f"CREATE TRIGGER {table}_set_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # --- Hand-added: reverse of the trigger block above, first, since the
    # functions cannot be dropped while a trigger still references them ---
    for table in ("cases", "mandates", "bench_runs"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_set_updated_at ON {table};")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.execute("DROP TRIGGER IF EXISTS audit_no_delete ON audit_events;")
    op.execute("DROP TRIGGER IF EXISTS audit_no_update ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_index('scheduled_expired_claims', table_name='scheduled_actions', postgresql_where=sa.text("status = 'claimed'"))
    op.drop_index('scheduled_due', table_name='scheduled_actions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('scheduled_actions')
    op.drop_table('policy_decisions')
    op.drop_table('planned_steps')
    op.drop_table('hypotheses')
    op.drop_table('plans')
    op.drop_table('payments')
    op.drop_table('outcomes')
    op.drop_table('diagnoses')
    op.drop_index('audit_kind_time', table_name='audit_events')
    op.drop_index('audit_case_seq', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('actions')
    op.drop_index('cases_open_dedup', table_name='cases', postgresql_where=sa.text("state NOT IN ('recovered','partially_recovered','lost','expired','suppressed')"))
    op.drop_table('cases')
    op.drop_table('signals')
    op.drop_table('mandates')
    op.drop_table('customer_pii')
    op.drop_index('contact_lookup', table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_index('consent_lookup', table_name='consent_events')
    op.drop_table('consent_events')
    op.drop_table('raw_events')
    op.drop_table('customers')
    op.drop_table('bench_runs')
    # ### end Alembic commands ###
